openapi: 3.0.3
info:
  title: User Service
  description: Service for managing users
  version: "1.0"
servers:
- url: http://localhost:8000
paths:
  /login/invite:
    post:
      tags:
      - users
      summary: invite users
      operationId: users#invite
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InviteRequestBody'
            example:
              user:
                email: test@test.com
                organisationID: 0763c56a-673b-4d30-9777-43cb1720ddfb
                password: Password!1
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthUserResponse'
              example:
                status: success
  /openapi.json:
    get:
      tags:
      - users
      summary: Download ./gen/http/openapi.json
      operationId: users#/openapi.json
      responses:
        "200":
          description: File downloaded
components:
  schemas:
    AuthUserResponse:
      type: object
      properties:
        status:
          type: string
          description: Status of the performed request
          example: success
          enum:
          - success
          - failure
      example:
        status: success
    InviteRequestBody:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/LoginInviteBody'
      example:
        user:
          email: test@test.com
          organisationID: 0763c56a-673b-4d30-9777-43cb1720ddfb
          password: Password!1
    LoginInviteBody:
      type: object
      properties:
        email:
          type: string
          description: New user email
          example: test@test.com
        organisationID:
          type: string
          description: ID of the organisation he was invited to
          example: 0763c56a-673b-4d30-9777-43cb1720ddfb
        password:
          type: string
          description: New user password
          example: Password!1
      description: Type sent to login/invite method
      example:
        email: test@test.com
        organisationID: 0763c56a-673b-4d30-9777-43cb1720ddfb
        password: Password!1
      required:
      - email
      - password
      - organisationID
tags:
- name: users
